#!/bin/bash
service=sizebot

bot=`basename $0`
cmd=$1
opt=$2

if [ "$cmd" = "start" ]; then
  systemctl --user start $service
elif [ "$cmd" = "stop" ]; then
  systemctl --user stop $service
elif [ "$cmd" = "restart" ]; then
  systemctl --user restart $service
elif [ "$cmd" = "status" ]; then
  systemctl --no-pager --user status $service
elif [ "$cmd" = "log" ]; then
  logopt="-n 20 --no-pager -o cat"
  if [[ "$opt" =~ ^[0-9]+$ ]]; then
    logopt="-n $opt -o cat"
  elif [ "$opt" = "-f" ]; then
    logopt="-f -o cat"
  fi
  echo LOGOPT: $logopt
  journalctl --user -u $service $logopt
else
  echo Usage: $bot [start/stop/restart/status/log]
fi

